version: '3'

services:
  web:
    environment:
      - DJANGO_DEBUG=true
    command:
      sh -c "
        pytest
        && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"

  celery:
    command: celery -A network_audit worker -l info

  celery_beat:
    command: celery -A network_audit beat -l info
